---
abstract: 'Convert texts like which a cat is talking in Japanese'
author:
  - 'azumakuniyuki <perl.org [at] azumakuniyuki.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Nyaa
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Module::Load: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: origin
version: 0.000005
